version: "3.3"

services:
  db:
    image: postgres
    container_name: chatterbox-db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}    
    ports:
      - "5432:5432"
    networks:
      chatterbox-net:
        ipv4_address: 175.84.0.4 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5        
  backend:
    build: .
    depends_on: 
      - db
    container_name: chatterbox-backend
    restart: always
    ports: 
      - "8000:8000"
      - "9000:9000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=175.84.0.4
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_BUCKET_URL=${S3_BUCKET_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    networks:
      chatterbox-net:
        ipv4_address: 175.84.0.3
  frontend:
    build: frontend
    depends_on:
      - backend
    container_name: chatterbox-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_HTTPS=true      
    networks:
      chatterbox-net:
        ipv4_address: 175.84.0.2   
networks:
  chatterbox-net:
    external: true

